### ISSUE TITLE
Is the namecheap plugin compatible with ACMEv2?

### ISSUE THREAD

**Issue by gilgameshskytrooper** [caddyserver/dnsproviders#28] opened 2018-04-16 01:50 UTC
I am having trouble with updating Caddy to v0.10.11 to v0.10.12 and a gentleman on my Issues thread suggested this might be a fault in the plugin I am using (namecheap).

I was wondering if this could be the case?

Thanks

**Comment by mholt** [comment] 2018-04-16 01:54
What is the trouble you're having?

**Comment by gilgameshskytrooper** [comment] 2018-04-16 01:54
https://github.com/mholt/caddy/issues/2116

**Comment by mholt** [comment] 2018-04-16 01:56
To answer your question -- yes, it's compatible; I still think the issue is somewhere with your DNS or with Namecheap. I'm gonna close this and take it back there until we are convinced that the issue is with the Namecheap provider plugin (it almost always isn't -- this package just calls out to xenolf/lego/providers/namecheap.)

**Closed by mholt** 2018-04-16 01:56 UTC
